# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "lightmix-0.20.3-SpCovOyWAgA1qLyV9vSywrsPz2fENpqCrJLqZqJRJjEJ";
    path = fetchzip {
      url = "https://codeload.github.com/haruki7049/lightmix/tar.gz/refs/tags/0.20.3";
      hash = "sha256-Q954n/kf3vzlX835S3VZ7AcrZWoNBnKE7PXo5f0HnQA=";
    };
  }
  {
    name = "riff_zig-1.0.0-J7H0A7E6TAAFStkejtsMRsIhfgLMLzf5iYxWgeSFBLJu";
    path = fetchzip {
      url = "https://codeload.github.com/haruki7049/RIFF.zig/tar.gz/refs/tags/1.0.0";
      hash = "sha256-ELlLnVXNOfI44m9EbnKAsaWMjDKEAP1i0VnIdv1Tq14=";
    };
  }
  {
    name = "system_sdk-0.3.0-dev-alwUNnYaaAJAtIdE2fg4NQfDqEKs7QCXy_qYukAOBfmF";
    path = fetchzip {
      url = "https://codeload.github.com/zig-gamedev/system_sdk/tar.gz/c0dbf11cdc17da5904ea8a17eadc54dee26567ec";
      hash = "sha256-O3+Z4F58yESes3AMR3yfgqzJjM35BjwxGULgjKgJ6cE=";
    };
  }
  {
    name = "zaudio-0.11.0-dev-_M-91kHvPwAlW8MCRI4XiTbTeihqB8Zspgiuw-6Gqgdz";
    path = fetchzip {
      url = "https://codeload.github.com/zig-gamedev/zaudio/tar.gz/bb93ad665b89e302d4515a36b44cb8e73eaf6766";
      hash = "sha256-iMGK3w/SQ6IxD2vW1x0nwKshhdzNLAsbngx0Vo1Svgc=";
    };
  }
  {
    name = "zigggwavvv-1.0.0-iR5xWiDEAAD6QVEQLTO2j1OfcisaJgUfwo0hLAJnb6hS";
    path = fetchzip {
      url = "https://codeload.github.com/haruki7049/zigggwavvv/tar.gz/refs/tags/1.0.0";
      hash = "sha256-XBhbXfS7KJlIuchKeTPYoMZrZvaCXuWNX+eWLxkdV0s=";
    };
  }
]
